Fabric.Authorization.API/Services/CouchDbAccessService.cs
While performance testing I noticed our database activity is really high, one potential reason for that is we create two connections per query, one to check if the db exists, then another to perform the query.  Here I am removing the call to check that the database exists before performing the query because in theory we setup the db during app startup.
=> removed extraneous database calls occuring before every query

Fabric.Authorization.API/Bootstrapper.cs, Fabric.Authorization.API/Constants/HttpResponseHeaders.cs, Fabric.Authorization.API/Infrastructure/PipelineHooks/OnErrorHooks.cs, Fabric.Authorization.API/Infrastructure/PipelineHooks/RequestHooks.cs, Fabric.Authorization.API/Startup.cs, Fabric.Authorization.IntegrationTests/Modules/ClientTests.cs, Fabric.Authorization.IntegrationTests/Modules/GroupsTests.cs, Fabric.Authorization.IntegrationTests/Modules/PermissionsTests.cs, Fabric.Authorization.IntegrationTests/Modules/RolesTests.cs, Fabric.Authorization.IntegrationTests/Modules/UserTests.cs, Fabric.Authorization.UnitTests/ModuleTestsBase.cs
i added a handler for dealing with unhandled exceptions (approach taken from here https://bytefish.de/blog/consistent_error_handling_with_nancy/). this way we can set a custom message and more importantly add the CORS headers to the response so that javascript applications can read the response. currently it only handles unhandled exceptions but in the future we can add handling for 404's and in the platform middleware we should be able to handle 403's. relevant code is in the class OnErrorHooks
i also moved the cors headers to the HttpResponseHeaders class so we can reuse them.
=> added handler for unhandled exceptions 

Fabric.Authorization.API/Constants/Claims.cs, Fabric.Authorization.API/Models/ModelExtensions.cs, Fabric.Authorization.API/Models/UserApiModel.cs, Fabric.Authorization.API/Modules/FabricModule.cs, Fabric.Authorization.API/Modules/GroupsModule.cs, Fabric.Authorization.API/Modules/UsersMetadataModule.cs, Fabric.Authorization.API/Modules/UsersModule.cs, Fabric.Authorization.API/RemoteServices/Identity/Models/UserSearchRequest.cs, Fabric.Authorization.API/RemoteServices/Identity/Providers/IdentityServiceProvider.cs, Fabric.Authorization.Domain/Models/Formatters/Formatters.cs, Fabric.Authorization.Domain/Models/Formatters/IIdentifierFormatter.cs, Fabric.Authorization.Domain/Models/GranularPermission.cs, Fabric.Authorization.Domain/Models/User.cs, Fabric.Authorization.Domain/Stores/CouchDB/CouchDbUserStore.cs, Fabric.Authorization.Domain/Stores/InMemory/InMemoryUserStore.cs, Fabric.Authorization.Domain/Stores/Services/GroupService.cs, Fabric.Authorization.Domain/Stores/Services/UserService.cs, Fabric.Authorization.IntegrationTests/Modules/GroupsTests.cs, Fabric.Authorization.IntegrationTests/Modules/IdentitySearchTests.cs, Fabric.Authorization.IntegrationTests/Modules/UserTests.cs, Fabric.Authorization.UnitTests/Mocks/UserStoreMockExtensions.cs, Fabric.Authorization.UnitTests/Search/IdentitySearchServiceTests.cs, Fabric.Authorization.UnitTests/Users/UsersModuleTests.cs
get identity provider from claims when finding permissions for a user
when searching for user use the userid (subjectid:identityprovider)
added identityprovider to endpoint for getting a users groups
=> ensure subject is used instead of userid. 

Fabric.Authorization.API/Bootstrapper.cs, Fabric.Authorization.API/Infrastructure/PipelineHooks/RequestHooks.cs, Fabric.Authorization.IntegrationTests/Modules/ClientTests.cs, Fabric.Authorization.UnitTests/ModuleTestsBase.cs
the model binding breaks in nancy if there is a content-type header set for get requests. i added a request hook to remove it if its present
=> remove content type header for get requests

Fabric.Authorization.API/Bootstrapper.cs, Fabric.Authorization.API/Services/CouchDbAccessService.cs
This will lock down the individual authorization database so only the server admin or the created user can access it.
=> Added code to create a user when initializing the CouchDB database.

Fabric.Authorization.API/Models/ModelExtensions.cs, Fabric.Authorization.API/Models/Search/Validators/IdentitySearchRequestValidator.cs, Fabric.Authorization.API/ModuleExtensions/ModuleValidation.cs, Fabric.Authorization.API/Modules/ClientsModule.cs, Fabric.Authorization.API/Modules/SecurableItemsModule.cs, Fabric.Authorization.Domain/Validators/ClientValidator.cs, Fabric.Authorization.Domain/Validators/GroupValidator.cs, Fabric.Authorization.Domain/Validators/PermissionValidator.cs, Fabric.Authorization.Domain/Validators/RoleValidator.cs, Fabric.Authorization.Domain/Validators/SecurableItemValidator.cs, Fabric.Authorization.Domain/Validators/ValidationEnums.cs, Fabric.Authorization.IntegrationTests/CouchDB/CouchDBGroupsTests.cs, Fabric.Authorization.IntegrationTests/IntegrationTestsFixture.cs, Fabric.Authorization.IntegrationTests/Modules/ClientTests.cs, Fabric.Authorization.IntegrationTests/Modules/GroupsTests.cs, Fabric.Authorization.IntegrationTests/Modules/PermissionsTests.cs, Fabric.Authorization.IntegrationTests/Modules/RolesTests.cs, Fabric.Authorization.UnitTests/Clients/ClientsModuleTests.cs, Fabric.Authorization.UnitTests/Permissions/PermissionsModuleTests.cs, Fabric.Authorization.UnitTests/SecurableItems/SecurableItemsModuleTests.cs
added a CustomState to the model validation errors so when we are building the validation response for the client we can return a 409 if there is an attempt to add a duplicate resource
=> enhance model validation so we can return different status codes 

Fabric.Authorization.Domain/Stores/CouchDB/CouchDBGroupStore.cs, Fabric.Authorization.Domain/Stores/IGroupStore.cs, Fabric.Authorization.Domain/Stores/InMemory/InMemoryGroupStore.cs, Fabric.Authorization.Domain/Stores/Services/GroupService.cs, Fabric.Authorization.Persistence.SqlServer/Stores/SqlServerGroupStore.cs, Fabric.Authorization.UnitTests/Search/IdentitySearchServiceTests.cs
one thing about this approach is i had to move all the code out of the service and into the store methods. the service class basically becomes a pass through. this is because the store methods return domain models and i did not want to have to query again for entities in the sql server store implementation. we can discuss tomorrow morning
=> moved db specific stuff out of the GroupService class and into the store implementations

Fabric.Authorization.API/Services/CouchDbAccessService.cs, Fabric.Authorization.IntegrationTests/CouchDB/CouchDBGroupsTests.cs, Fabric.Authorization.IntegrationTests/IntegrationTestsFixture.cs, Fabric.Authorization.IntegrationTests/Modules/GroupsTests.cs, Fabric.Authorization.Persistence.SqlServer/Stores/SqlServerGroupStore.cs
there is one test in CouchDbGroupsTests.cs that i have ignored for now because it keeps failing because the record is not found even though the record exists in the database and the document id matches exactly. its not a huge deal because its a test to cover the old style group ids (not sure what that is exactly) but we wont have that problem in production.
=> refactor group integration tests

Fabric.Authorization.API/Bootstrapper.cs, Fabric.Authorization.API/Configuration/AppConfiguration.cs, Fabric.Authorization.API/Configuration/IAppConfiguration.cs, Fabric.Authorization.API/Constants/StorageProviders.cs, Fabric.Authorization.API/Startup.cs, Fabric.Authorization.API/appsettings.json, Fabric.Authorization.Domain/Stores/AuditingDocumentDbService.cs, Fabric.Authorization.Domain/Stores/CachingDocumentDbService.cs, Fabric.Authorization.Domain/Stores/CouchDB/CouchDbBootstrapper.cs, Fabric.Authorization.Domain/Stores/IDbBootstrapper.cs, Fabric.Authorization.Domain/Stores/IDocumentDbService.cs, Fabric.Authorization.Domain/Stores/InMemory/InMemoryDbBootstrapper.cs, Fabric.Authorization.IntegrationTests/CouchDB/CouchClientTests.cs, Fabric.Authorization.IntegrationTests/CouchDB/CouchDBGroupsTests.cs, Fabric.Authorization.IntegrationTests/CouchDB/CouchDBPermissionsTests.cs, Fabric.Authorization.IntegrationTests/CouchDB/CouchDBRolesTests.cs, Fabric.Authorization.IntegrationTests/CouchDB/CouchDBUserTests.cs, Fabric.Authorization.IntegrationTests/CouchDB/CouchDbIdentitySearchTests.cs, Fabric.Authorization.IntegrationTests/IntegrationTestsFixture.cs, Fabric.Authorization.IntegrationTests/Modules/ClientTests.cs, Fabric.Authorization.IntegrationTests/Modules/GroupsTests.cs, Fabric.Authorization.IntegrationTests/Modules/IdentitySearchTests.cs, Fabric.Authorization.IntegrationTests/Modules/PermissionsTests.cs, Fabric.Authorization.IntegrationTests/Modules/RolesTests.cs, Fabric.Authorization.IntegrationTests/Modules/UserTests.cs, Fabric.Authorization.Persistence.SqlServer/Services/SqlServerDbBootstrapper.cs
Sorry for the size of the PR, most of the changes are small, but I did do a little refactoring in the bootstrapper to simplify it a bit. I also extracted an IDbBootstrapper interface like we have in Identity.
=> Add a StorageProvider config so we can switch between more than two storage providers.

Fabric.Authorization.IntegrationTests/Modules/ClientTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerClientTests.cs, Fabric.Authorization.Persistence.SqlServer/Mappers/ClientMapper.cs, Fabric.Authorization.Persistence.SqlServer/Mappers/ClientMapperProfile.cs, Fabric.Authorization.Persistence.SqlServer/Mappers/GroupMapper.cs, Fabric.Authorization.Persistence.SqlServer/Mappers/PermissionMapper.cs, Fabric.Authorization.Persistence.SqlServer/Mappers/RoleMapper.cs, Fabric.Authorization.Persistence.SqlServer/Mappers/SecurableItemMapper.cs, Fabric.Authorization.Persistence.SqlServer/Mappers/SecurableItemMapperProfile.cs, Fabric.Authorization.Persistence.SqlServer/Mappers/UserMapper.cs, Fabric.Authorization.Persistence.SqlServer/Services/SqlServerDbBootstrapper.cs, Fabric.Authorization.Persistence.SqlServer/Stores/SqlServerClientStore.cs
changed the way automapper profiles are initialized, they are all initialized by the sql server bootstrapper
fixed up the securable item mapping
=> get client tests passing for sql server

Fabric.Authorization.Persistence.SqlServer/Extensions/ModelBuilderExtensions.cs, Fabric.Authorization.Persistence.SqlServer/Mappers/RoleMapperProfile.cs, Fabric.Authorization.Persistence.SqlServer/Mappers/SecurableItemMapperProfile.cs, Fabric.Authorization.Persistence.SqlServer/Services/SqlServerDbBootstrapper.cs
also updated the SqlDbBootstrapper code that initializes the automapper profiles to use the SqlDbBootstrapper as the type in the assembly to scan to reduce confusion.
=> fixes to get roles handled properly by EF and automapper

Fabric.Authorization.IntegrationTests/IntegrationTestsFixture.cs, Fabric.Authorization.IntegrationTests/Modules/ClientTests.cs, Fabric.Authorization.IntegrationTests/Modules/DosTests.cs, Fabric.Authorization.IntegrationTests/Modules/GroupsTests.cs, Fabric.Authorization.IntegrationTests/Modules/IdentitySearchTests.cs, Fabric.Authorization.IntegrationTests/Modules/PermissionsTests.cs, Fabric.Authorization.IntegrationTests/Modules/RolesTests.cs, Fabric.Authorization.IntegrationTests/Modules/UserTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerClientTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerDosTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerGroupsTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerIdentitySearchTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerPermissionsTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerRolesTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerUserTests.cs, Fabric.Authorization.IntegrationTests/SqlServerIntegrationTestsFixture.cs
Our integration tests take over 6 minutes on the build server. Hopefully this will reduce that by not creating a database for every test class, and only creating a database per test run.
Also, added cleanup so we can potentially point the tests at a beefier sql server instance running on a VM instead of using a container on the build machine itself.
=> Only create one database per test run. Clean up database after test run.

Fabric.Authorization.AccessControl/src/app/app.module.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/access-control.module.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/member-list/member-list.component.ts, Fabric.Authorization.AccessControl/src/app/services/access-control-config.service.spec.ts, Fabric.Authorization.AccessControl/src/app/services/access-control-config.service.ts, Fabric.Authorization.AccessControl/src/app/services/global/client-access-control-config.service.ts, Fabric.Authorization.AccessControl/src/app/services/global/client-access-token.service.spec.ts, Fabric.Authorization.AccessControl/src/app/services/interceptors/fabric-http-interceptor.service.ts
the idea is that the app that installs the access control module will create a service that implements the functions and sets the properties we need to access the backend services (i.e. api urls, access token, client id). we can then import that service into any access control module services that require backend services.
=> added a config service for providing configuration data and functions to the access control module

Fabric.Authorization.API/Bootstrapper.cs, Fabric.Authorization.API/Fabric.Authorization.API.csproj, Fabric.Authorization.API/Startup.cs, Fabric.Authorization.IntegrationTests/Modules/UserTests.cs, Fabric.Authorization.IntegrationTests/TestBootstrapper.cs, Fabric.Authorization.Persistence.SqlServer/Services/AuthorizationDbContext.cs, Fabric.Authorization.Persistence.SqlServer/Services/InMemoryAuthorizationDbContext.cs, Fabric.Authorization.Persistence.SqlServer/Stores/SqlServerClientStore.cs, Fabric.Authorization.Persistence.SqlServer/Stores/SqlServerGroupStore.cs, Fabric.Authorization.Persistence.SqlServer/Stores/SqlServerPermissionStore.cs, Fabric.Authorization.Persistence.SqlServer/Stores/SqlServerRoleStore.cs, Fabric.Authorization.Persistence.SqlServer/Stores/SqlServerUserStore.cs, Fabric.Authorization.UnitTests/DbBootstrappers/SqlServerDbBootstrapperTests.cs
update all sql stores to remove code that will cause a client evaluation. some of the things that needed to be fixed: 
- dont call any methods on the string object inside a lambda used for filtering an EF query ( string.equals(a,b)
- create local variables when accessing items from an array, pass the local variables to the query ( dont grab an item from an array by index )
- dont use linq projections inside a query ( coll.Select(f => f.id).contains(bar) )   
i also enabled EF query logging
=> throw exception from EF if local evaluation of a query is going to happen

Fabric.Authorization.API/scripts/Install-Authorization-Windows.ps1
At the end of the script, I added a query to get the users and groups from EDWAdmin, then iterated over the list and called the already existing `Add-AccountToDosAdminRole` which does all the error checking and adds it to the right table based on whether it is a group or a user.
I also fixed the formatting according to my VS Code preferences... That's a lot of changes and I'm happy to undo them if you prefer. Just let me know. I'll highlight the changes in the PR
=> Adding upgrade functionality to move EDWAdmin roles to Fabric.Auth roles

Fabric.Authorization.API/Configuration/AppConfiguration.cs, Fabric.Authorization.API/Configuration/IAppConfiguration.cs, Fabric.Authorization.API/Logging/LogFactory.cs, Fabric.Authorization.API/Modules/FabricModule.cs, Fabric.Authorization.API/Startup.cs, Fabric.Authorization.API/appsettings.json, Fabric.Authorization.Persistence.SqlServer/Configuration/EntityFrameworkSettings.cs, Fabric.Authorization.Persistence.SqlServer/Fabric.Authorization.Persistence.SqlServer.csproj
I ended up making this configurable based on a minimum `LogEventLevel` so that we still get DB exceptions logged.
=> made logging of DB queries configurable

Fabric.Authorization.API/scripts/Install-Authorization-Windows.ps1
Trim ending slash after prompting user input for discovery url so either user input or already existing discovery url has it's ending slash removed
=> Trim ending discovery slash

Fabric.Authorization.API/scripts/run-client-functional-tests.sh
Added option -i to switch between local code and running dockerhub image
- Added a loop to parse the args for the "-i"
- Added a switch to name whether the disk comes from docker hub or local, and if it is local then build the image
-identity-setup-samples.sh needed an arg because it was using the parent script's args and that was causing issues.
=> Added option -i to switch between local code and running dockerhub image

Fabric.Authorization.Client.UnitTests/Fabric.Authorization.Client.UnitTests.csproj, Fabric.Authorization.Client/Fabric.Authorization.Client.csproj, Fabric.Authorization.Models/Fabric.Authorization.Models.csproj
Added code that will package project references using a build target.  The target works by looking for PrivateAssets="all", which indicates it is part of this package (Not something that is public like in a nuget repo.).  If this is not included, then the nuget pack will assume the reference is in nuget repo and it will not pull in those resources.
=> Added nuget target to include project references properly

Catalyst.Fabric.Authorization.Client.UnitTests/AuthorizationClientTests.cs, Catalyst.Fabric.Authorization.Client.UnitTests/Routes/ClientRouteTests.cs, Catalyst.Fabric.Authorization.Client.UnitTests/Routes/GroupRouteTests.cs, Catalyst.Fabric.Authorization.Client.UnitTests/Routes/MemberSearchRouteTests.cs, Catalyst.Fabric.Authorization.Client.UnitTests/Routes/PermissionRouteTests.cs, Catalyst.Fabric.Authorization.Client.UnitTests/Routes/RoleRouteTests.cs, Catalyst.Fabric.Authorization.Client.UnitTests/Routes/UserRouteTests.cs, Catalyst.Fabric.Authorization.Client/AuthorizationClient.cs, Catalyst.Fabric.Authorization.Client/Extensions/AuthorizationExtensions.cs, Catalyst.Fabric.Authorization.Client/Routes/BaseRoute.cs
This corrects the issue where forward slashes cause processing incorrect urls.
1. base url needs to have a forward slash
2. relative url paths should not have a forward slash at the beginning
I have updated the unit tests to reflect both scenarios.
=> Corrected forward slash issue.

Fabric.Authorization.API/scripts/Install-Authorization-Windows.ps1, Fabric.Authorization.Domain/Defaults/Authorization.cs, Fabric.Authorization.IntegrationTests/Modules/DosTests.cs, Fabric.Authorization.UnitTests/DbBootstrappers/SqlServerDbBootstrapperTests.cs
Associate the DataMartAdmin role to the DosAdmin group.
Move users/groups associated w/ the deprecated dosadmin role to the DosAdmin group.
Handle the case where someone may run the Fabric.Registration step before the Fabric.Authorization installation step.
=> Migrate dosadmin role to DataMartAdmin

Fabric.Authorization.AccessControl/src/app/services/interceptors/index.ts, Fabric.Authorization.AccessControl/src/app/services/interceptors/standard-header-interceptor.ts
Do not cache any requests made from access-control
=> IE no-cache required headers

Fabric.Authorization.AccessControl/src/index.html
Fixes the disappearing edge favicon which was caused because edge would request the favicon based on the page the browser was on instead of off the root
e.g. `/client/access-control-dos/favicon.ico` when on any dos grain securable instead of `/client/favicon.ico`
=> favicon off absolute path from root for edge(/ie bookmarking)

Fabric.Authorization.AccessControl/src/app/modules/access-control/member-list/member-list.component.html, Fabric.Authorization.AccessControl/src/app/modules/access-control/member-list/member-list.component.spec.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/member-list/member-list.component.ts
If displayName was empty, null or undefined, then try to use groupName
If groupName is empty, null or undefined, then display generic value so that the user has a link to click.
If there are other values to display other than group or display name, we can add to this code.
=> Added function to display a group or user name

Fabric.Authorization.AccessControl/src/app/modules/access-control/custom-group/custom-group.component.html, Fabric.Authorization.AccessControl/src/app/modules/access-control/custom-group/custom-group.component.spec.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/custom-group/custom-group.component.ts
I added the same code but slightly modified from member list.  This just makes sure there is a display name, and if there isnt, then uses group name.
There are tests to verify this.
=> Added code to failback to group name for display name

Fabric.Authorization.Domain/Services/GroupMigratorService.cs, Fabric.Authorization.IntegrationTests/Services/GroupMigratorServiceTests.cs
This bug surfaced in the SqlServer version of the integration test but not the in-memory version since the string equality comparison (`==`) is case sensitive when using the in-memory store so only 1 record was always returned with the query.
=> delete duplicate groups before merging to fix SingleOrDefault exception

Fabric.Authorization.AccessControl/src/app/modules/access-control/custom-group/custom-group.component.ts
I updated the `CustomGroupComponent` to use the config service to get a default identity provider if it needs to create custom child groups and users.
=> injected default provider

Fabric.Authorization.AccessControl/src/app/navbar/navbar.component.spec.ts, Fabric.Authorization.AccessControl/src/app/navbar/navbar.component.ts
Considering each identity provider will have a different profile object, I split the parsing off for Azure AD.  I more robust solution can come up in the future.
The parsing is a bit tedious, but the code is done.
=> Added Azure AD user name parsing for the navbar

Fabric.Authorization.AccessControl/src/app/services/fabric-auth-group.service.ts
Added logic to not send the child group deletion if no groups changed.  To fully "fix" the issue we'll also want to add some notes that if you're removing yourself from the group that is the only operation you should perform - you shouldn't attempt to remove other users, groups or roles.
=> Added code to only send group delete if actual groups change

Fabric.Authorization.AccessControl/src/app/no-cookies.app.module.ts, Fabric.Authorization.AccessControl/src/app/no-cookies/no-cookies.component.html, Fabric.Authorization.AccessControl/src/app/no-cookies/no-cookies.component.scss, Fabric.Authorization.AccessControl/src/app/no-cookies/no-cookies.component.spec.ts, Fabric.Authorization.AccessControl/src/app/no-cookies/no-cookies.component.ts, Fabric.Authorization.AccessControl/src/app/services/browser-requirements.service.spec.ts, Fabric.Authorization.AccessControl/src/app/services/browser-requirements.service.ts, Fabric.Authorization.AccessControl/src/main.ts
This PR pertains to bug [162684](https://healthcatalyst.visualstudio.com/CAP/_workitems/edit/162684). 
Within `main.ts` use the new `BrowserRequirementsService`'s `cookiesEnabled` method to test whether or not cookies are enabled. If they are not bootstrap the new `no-cookies.app` instead of the main application. The main application itself requires cookies along with local and session storage (as controlled by browsers cookies settings). By creating the `no-cookies.app` we can provide the user with an appropriately styled error page. The error page will retest for cookies and reload the application when cookie support is re-enabled.
=> Display error page when cookies are not enabled

Fabric.Authorization.AccessControl/src/app/services/global/services.service.ts
With the mock, this was missed.  Basically if the service is using windows auth, it will not require an auth token.  This will be false.  If the discovery service is using OAuth, then it will be true.
=> Discovery Url for Windows Auth needs false

Fabric.Authorization.AccessControl/src/app/services/access-control-config.service.mock.ts, Fabric.Authorization.AccessControl/src/app/services/access-control-config.service.ts, Fabric.Authorization.AccessControl/src/app/services/fabric-base.service.ts, Fabric.Authorization.AccessControl/src/app/services/global/client-access-control-config.service.ts, Fabric.Authorization.AccessControl/src/app/services/global/services.service.ts
The previous code was causing a race condition as well as calling build service maps every time a service was created.  This would call discovery service too many times.  We found it was only needed to be called from the initializer.
=> moved the buildServiceMaps back into the initializer to avoid weird bugs

Fabric.Authorization.AccessControl/src/app/no-cookies/no-cookies.component.ts
Somehow using window.location.reload() causes the angular tests to be ran multiple times. Changing to this.ngOnInit eliminated that when I ran them locally.
=> Changed the way the component was reloaded to eliminate tests running multiple times

Fabric.Authorization.API/scripts/AzureAD-Groups-Migration.ps1, Fabric.Authorization.API/scripts/AzureAD-Users-Migration.ps1, Fabric.Authorization.API/scripts/AzureAD-Utilities.psm1, Fabric.Authorization.API/scripts/Install-Authorization-Utilities.psm1, Fabric.Authorization.API/scripts/Install-Authorization-Utilities.tests.ps1, Fabric.Authorization.API/scripts/Install-Authorization.ps1
Using the newly introduced "Get-WebRequestDownload" function in DosInstallUtilities to remove the progress bar when downloading assets for installation.
=> Remove progress bar when downloading assets during installation

Fabric.Authorization.API/Dockerfile, Fabric.Authorization.AccessControl/src/app/modules/access-control/custom-group/custom-group.component.spec.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/custom-group/custom-group.component.ts, Fabric.Authorization.AccessControl/src/app/services/current-user.service.ts, Fabric.Authorization.AccessControl/src/app/services/global/auth.service.mock.ts
Fixed the issue when the user removes themselves from the DOS Admin group, if you quickly go back in the group, the permsission cache is still active and you can see an 'Enabled' Save button.
=> Fixing issue where user removes self from group

Fabric.Authorization.AccessControl/src/app/modules/access-control/member-list/member-list.component.html
Changed from showing the subject Id to the display name since Azure AD's subject id isn't user friendly.
=> Changed from showing subject Id to display name

Fabric.Authorization.API/scripts/AzureAD-Users-Migration.ps1
Updated reference to $tenants variable on line 538.  Existing reference was pulling entire hashtable value instead of the tenant name value
=> updated $tenants variable reference

Fabric.Authorization.API/scripts/AzureAD-Users-Migration.ps1, Fabric.Authorization.API/scripts/Install-Authorization-Utilities.psm1
2 scenarios:
1. This scenario.  We get the user and split it by its subject id to get Username and Domain.  Do a search and map this to AzureAD.  There were redundant calls that were removed.  Created a function to give the domain part of the name too.
2. The previous code took in a domain name.  Do we want to search AD just for the domain we have from the currently logged in user?  If we are scanning the database it makes sense to pull all users regardless of domain and map them based on that.  We will want to see how this may work.
Need some thoughts to get my head around this.
=> use domain of user for querying

Fabric.Authorization.API/scripts/AzureAD-Users-Migration.ps1, Fabric.Authorization.API/scripts/Install-Authorization-Utilities.tests.ps1
@ctediz I missed your comment about the subjectId having a better output.  I have added a try catch to see if we can skip those.
Also added tests for the Get-SamAccountFromAccountName function
=> Added Tests and printed better message for invalid account names.

Fabric.Authorization.AccessControl/protractor.conf.js
Still not fully logging in when hitting the api,
but this accepts the credentials and should get the functional tests up and running in the meantime
=> Login to discovery using windows auth

Catalyst.Fabric.Authorization.Client.FunctionalTests/Catalyst.Fabric.Authorization.Client.FunctionalTests.csproj, Catalyst.Fabric.Authorization.Client.UnitTests/Catalyst.Fabric.Authorization.Client.UnitTests.csproj, Fabric.Authorization.API/Bootstrapper.cs, Fabric.Authorization.API/Dockerfile, Fabric.Authorization.API/Extensions/TinyIocExtensions.cs, Fabric.Authorization.API/Fabric.Authorization.API.csproj, Fabric.Authorization.API/Program.cs, Fabric.Authorization.API/Services/HttpRequestMessageFactory.cs, Fabric.Authorization.API/Startup.cs, Fabric.Authorization.API/scripts/Install-Authorization.ps1, Fabric.Authorization.API/scripts/run-integration-tests.sh, Fabric.Authorization.AccessControl/README.md, Fabric.Authorization.Domain/Fabric.Authorization.Domain.csproj, Fabric.Authorization.IntegrationTests/Fabric.Authorization.IntegrationTests.csproj, Fabric.Authorization.IntegrationTests/Services/GroupMigratorServiceTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerGroupMigratorServiceTests.cs, Fabric.Authorization.Persistence.SqlServer/Extensions/EDWModelBuilderExtensions.cs, Fabric.Authorization.Persistence.SqlServer/Fabric.Authorization.Persistence.SqlServer.csproj, Fabric.Authorization.Persistence.SqlServer/Services/AuthorizationDbContext.cs, Fabric.Authorization.UnitTests/Fabric.Authorization.UnitTests.csproj, docker-compose.dcproj
Upgrading Fabric.Authorization to .net core 2.1.10.
To build and run with this version ensure you have these versions of the SDK and hosting components:
- dotnet core sdk 2.1.603: https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-2.1.603-windows-x64-installer
- runtime and hosting bundle: https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-2.1.10-windows-hosting-bundle-installer
=> Upgrade to .net core 2.1.10

Fabric.Authorization.Persistence.SqlServer/Stores/SqlServerGroupStore.cs
This is a short term fix to let the app start - we have to get to the root cause of why the user object is null here. The query EF is running looks like the user object is being returned, its simply not being materialized in as an object in EF for some reason. This will unblock testing - but we need to revisit it.
=> Handle null when user is null during startup.

Fabric.Authorization.AccessControl/src/app/modules/access-control/custom-group/custom-group.component.spec.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/custom-group/custom-group.component.ts
If the user tries to create new custom group with a group name that already exists, the roles would get unchecked when they changed the group name.  So I added an if statement to see if the user got this error, and if so, then the roles wouldn't get unchecked.
=> Roles getting unchecked if group exists

Fabric.Authorization.API/scripts/Install-Authorization-Utilities.psm1, Fabric.Authorization.API/scripts/Install-Authorization.ps1
UseOAuth2Authentication is now being set through the Authorization install for AccessControl by using the discoveryservice scope in the install.config to determine if Oauth is enabled for discovery.
=> Add oauth web.config flag for access control during install

Fabric.Authorization.AccessControl/README.md, Fabric.Authorization.AccessControl/src/app/services/current-user.service.ts
There is a race condition occurring, due to the UI tests speeding through the initial member-list page which hits the current-user service.  Then the test navigates to the member page which also hits the user service. 
Occasionally, the api call to authorization would not yet be resolved so the UI test would get back the cached permissions which were still undefined.
=> 'bandaid' for race condition

Fabric.Authorization.AccessControl/src/app/services/global/services.service.spec.ts, Fabric.Authorization.AccessControl/src/app/services/global/services.service.ts, Fabric.Authorization.AccessControl/src/app/services/interceptors/fabric-http-fake-discovery-interceptor.service.ts
Client-side initialization included discovery service call for endpoints in ServicesService.
This still included "IdentityProviderSearchService" and can throw an error if no entry exists in discovery.
IdentityProviderSearchService has been removed from the list of services to look up.
- Removed function for retrieving idPSS endpoint from ServicesService
- Removed idPSS endpoint from FabricHttpFakeDiscoveryInterceptorService used in dev environment.
- Removed idPSS-specific tests for ServicesService spec.
- Modified other ServicesService spec tests contaiing mock entries for idPSS.
196692: Unable to log into Access Control with client side error related to idPSS
https://dev.azure.com/healthcatalyst/CAP/_workitems/edit/196692
=> Remove Access Control client check for idPSS endpoint in discovery
