Fabric.Authorization.API/scripts/Install-Authorization-Windows.ps1, Fabric.Authorization.API/scripts/install.config
Added prerequisite checked to Authorization install. Add ability to read config from file. Added registration steps.
=> Updated installation script

Fabric.Authorization.API/scripts/Install-Authorization-Windows.ps1
These are the changes needed to setup authorization as a client application during installation on windows.
=> Update powershell install script to register authorization as a client.

Fabric.Authorization.API/scripts/Install-Authorization-Windows.ps1, Fabric.Authorization.API/web.config
Made the installation script more robust by:
1 - Adding prerequisite checks for zip file, installer secret, access token, and encryption certificate
2 - Added an explicit allowAnonymous entry to the web.config
=> Installation script updates

Fabric.Authorization.API/scripts/Fabric.Authorization.nuspec, Fabric.Authorization.API/scripts/Fabric.Authorization.targets
=> Adding nuspec and targets file for packing Fabric.Authorization 

Fabric.Authorization.API/Extensions/TinyIocExtensions.cs, Fabric.Authorization.API/scripts/Fabric.Authorization.InstallPackage.nuspec, Fabric.Authorization.API/scripts/Fabric.Authorization.InstallPackage.targets
Updated nuspec and targets file so zip file gets copied on build properly
=> Updated nuspec and targets files

Fabric.Authorization.API/Modules/IdentitySearchModule.cs, Fabric.Authorization.API/Modules/RolesModule.cs, Fabric.Authorization.API/Modules/UsersModule.cs, Fabric.Authorization.Domain/Stores/InMemory/InMemoryGenericStore.cs, Fabric.Authorization.IntegrationTests/Modules/IdentitySearchTests.cs, Fabric.Authorization.IntegrationTests/Modules/RolesTests.cs, Fabric.Authorization.IntegrationTests/Modules/UserTests.cs
fixed a few places where we were returning the wrong status codes. 
added some tests to ensure the correct status codes are returned.
=> ensure the correct status codes are returned for different scenarios

Fabric.Authorization.Persistence.SqlServer/EntityModels/Client.cs, Fabric.Authorization.Persistence.SqlServer/EntityModels/SecurableItem.cs, Fabric.Authorization.Persistence.SqlServer/Fabric.Authorization.Persistence.SqlServer.csproj, Fabric.Authorization.Persistence.SqlServer/Mappers/ClientMapper.cs, Fabric.Authorization.Persistence.SqlServer/Mappers/ClientMapperProfile.cs, Fabric.Authorization.Persistence.SqlServer/Mappers/SecurableItemMapper.cs, Fabric.Authorization.Persistence.SqlServer/Mappers/SecurableItemMapperProfile.cs, Fabric.Authorization.Persistence.SqlServer/Services/AuthorizationDbContext.cs, Fabric.Authorization.Persistence.SqlServer/Services/IAuthorizationDbContext.cs
i need to figure out the best way to model the securableItems collection on the securableItem entity. Its supposed to represent the children securable items. 
i also left a placeholder string for created by and modified by until we have a way to pull the authenticated users name. i will add a task for it.
=> client and securable item entity models, mappers, and db context setup

Fabric.Authorization.Persistence.SqlServer/EntityModels/SecurableItem.cs, Fabric.Authorization.Persistence.SqlServer/Extensions/ModelBuilderExtensions.cs, Fabric.Authorization.Persistence.SqlServer/Services/AuthorizationDbContext.cs, Fabric.Authorization.Persistence.SqlServer/Stores/SqlServerClientStore.cs
also added null check in delete and update methods on the client store
=> fixed up EF relationships on securable item entity model

Fabric.Authorization.Persistence.SqlServer/EntityModels/GroupRole.cs, Fabric.Authorization.Persistence.SqlServer/EntityModels/GroupUser.cs, Fabric.Authorization.Persistence.SqlServer/EntityModels/User.cs, Fabric.Authorization.Persistence.SqlServer/EntityModels/UserPermission.cs, Fabric.Authorization.Persistence.SqlServer/Extensions/ModelBuilderExtensions.cs, Fabric.Authorization.Persistence.SqlServer/Stores/SqlServerGroupStore.cs, Fabric.Authorization.Persistence.SqlServer/Stores/SqlServerPermissionStore.cs
will follow up with the group service changes to take advantage of the new data model in a different PR
=> update entity models to leverage non identity column based PKs

Fabric.Authorization.API/Configuration/AppConfiguration.cs, Fabric.Authorization.API/Configuration/IAppConfiguration.cs, Fabric.Authorization.API/appsettings.json, Fabric.Authorization.Persistence.SqlServer/Configuration/ConnectionStrings.cs, Fabric.Authorization.Persistence.SqlServer/Configuration/IConnectionStrings.cs, Fabric.Authorization.Persistence.SqlServer/Fabric.Authorization.Persistence.SqlServer.csproj, Fabric.Authorization.Persistence.SqlServer/Services/AuthorizationDbContext.cs
I am not sure where to register the options so we can set the connection string via the DI container.
=> move dbcontext connection string to app config 

Fabric.Authorization.API/Startup.cs, Fabric.Authorization.IntegrationTests/IntegrationTestsFixture.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerClientTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerGroupsTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerIdentitySearchTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerPermissionsTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerRolesTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerUserTests.cs, Fabric.Authorization.IntegrationTests/TestBootstrapper.cs, Fabric.Authorization.Persistence.SqlServer/Extensions/ModelBuilderExtensions.cs, Fabric.Authorization.Persistence.SqlServer/Services/AuthorizationDbContext.cs
register sql server in dbcontext instead of in startup.cs
=> added sql server integration test classes

Fabric.Authorization.API/Dockerfile, Fabric.Authorization.API/scripts/run-all-tests.sh, Fabric.Authorization.API/scripts/run-functional-tests.sh, Fabric.Authorization.API/scripts/run-integration-tests.sh, Fabric.Authorization.API/scripts/run-unit-tests.sh, Fabric.Authorization.FunctionalTests/package-lock.json, Fabric.Authorization.FunctionalTests/package.json, Fabric.Authorization.FunctionalTests/tests/authorizationtests.js
Also added scripts to run unit/integration/functional tests.
=> Updated node packages to remove vulnerability

Fabric.Authorization.IntegrationTests/CouchDB/CouchClientTests.cs, Fabric.Authorization.IntegrationTests/CouchDB/CouchDBGroupsTests.cs, Fabric.Authorization.IntegrationTests/CouchDB/CouchDBPermissionsTests.cs, Fabric.Authorization.IntegrationTests/CouchDB/CouchDBRolesTests.cs, Fabric.Authorization.IntegrationTests/CouchDB/CouchDBUserTests.cs, Fabric.Authorization.IntegrationTests/CouchDB/CouchDbIdentitySearchTests.cs, Fabric.Authorization.IntegrationTests/IntegrationTestsFixture.cs, Fabric.Authorization.IntegrationTests/Modules/ClientTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerClientTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerGroupsTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerIdentitySearchTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerPermissionsTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerRolesTests.cs, Fabric.Authorization.IntegrationTests/SqlServer/SqlServerUserTests.cs, Fabric.Authorization.Persistence.CouchDb/Services/CouchDbBootstrapper.cs, Fabric.Authorization.Persistence.SqlServer/Stores/SqlServerClientStore.cs
for now i have disabled the couch db tests until i figure out why they cause a deadlock on the build server.
once i have the build pipeline updated with the steps for sql server i will commit this to master.
=> enable sql server integration tests

Fabric.Authorization.API/Models/ModelExtensions.cs, Fabric.Authorization.API/Modules/FabricModule.cs, Fabric.Authorization.API/Modules/UsersMetadataModule.cs, Fabric.Authorization.API/Modules/UsersModule.cs, Fabric.Authorization.Domain/Services/UserService.cs, Fabric.Authorization.Domain/Validators/UserValidator.cs, Fabric.Authorization.IntegrationTests/IntegrationTestsFixture.cs, Fabric.Authorization.IntegrationTests/Modules/UserTests.cs, Fabric.Authorization.UnitTests/Mocks/UserStoreMockExtensions.cs, Fabric.Authorization.UnitTests/ModuleTestsBase.cs, Fabric.Authorization.UnitTests/Users/UsersModuleTests.cs
So we can add a user before we assign roles to the user.
Created corresponding tests and swagger docs.
=> Added a POST /user endpoint

Fabric.Authorization.API/scripts/Install-Authorization-Windows.ps1, Fabric.Authorization.API/scripts/install.config, Fabric.Authorization.SqlServer/Fabric.Authorization.SqlServer.sqlproj, Fabric.Authorization.SqlServer/Security/AuthorizationServiceRole.sql
Added an AuthorizationServiceRole to the dacpac
Installer adds the app pool user to the role on install
Installer registers api and client with identity.
=> Updated authorization installer 

Fabric.Authorization.SqlServer/Fabric.Authorization.SqlServer.sqlproj, Fabric.Authorization.SqlServer/PublishProfiles/Fabric.Authorization.SqlServer.publish.xml, Fabric.Authorization.SqlServer/Storage/HCFabricAuthorizationLogFile1.sql
=> add sql cmd vars to project and matching naming in the profile

Fabric.Authorization.API/Models/Search/MemberSearchResponse.cs, Fabric.Authorization.API/Models/Search/MemberSearchResponseExtensions.cs, Fabric.Authorization.API/Modules/GroupsMetadataModule.cs, Fabric.Authorization.API/Modules/UsersMetadataModule.cs, Fabric.Authorization.API/Services/MemberSearchService.cs, Fabric.Authorization.AccessControl/src/app/models/authMemberSearchResult.model.ts, Fabric.Authorization.AccessControl/src/app/models/idpSearchRequest.model.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/access-control-routing.module.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/access-control.module.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/custom-group-add/custom-group-add.component.css, Fabric.Authorization.AccessControl/src/app/modules/access-control/custom-group-add/custom-group-add.component.html, Fabric.Authorization.AccessControl/src/app/modules/access-control/custom-group-add/custom-group-add.component.spec.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/custom-group-add/custom-group-add.component.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/member-add/member-add.component.html, Fabric.Authorization.AccessControl/src/app/modules/access-control/member-add/member-add.component.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/member-list/member-list.component.html, Fabric.Authorization.AccessControl/src/app/modules/access-control/member-list/member-list.component.ts, Fabric.Authorization.AccessControl/src/app/services/fabric-auth-member-search.service.spec.ts, Fabric.Authorization.AccessControl/src/app/services/fabric-external-idp-search.service.spec.ts, Fabric.Authorization.AccessControl/src/app/services/global/client-access-control-config.service.ts, Fabric.Authorization.IntegrationTests/Modules/MemberSearchTests.cs, Fabric.Authorization.UnitTests/Search/MemberSearchServiceTests.cs
updated member search response to include the role model for members instead of just the role id. 
fixed a minor bug in the groups metadata module
=> added component to add a custom group and associate with users and roles

Fabric.Authorization.AccessControl/src/app/app.module.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/access-control.module.ts, Fabric.Authorization.AccessControl/src/app/services/access-control-config.service.ts, Fabric.Authorization.AccessControl/src/app/services/fabric-auth-group.service.ts, Fabric.Authorization.AccessControl/src/app/services/fabric-auth-member-search.service.spec.ts, Fabric.Authorization.AccessControl/src/app/services/fabric-auth-member-search.service.ts, Fabric.Authorization.AccessControl/src/app/services/fabric-auth-role.service.ts, Fabric.Authorization.AccessControl/src/app/services/fabric-auth-user.service.ts, Fabric.Authorization.AccessControl/src/app/services/fabric-external-idp-search.service.ts, Fabric.Authorization.AccessControl/src/app/services/interceptors/fabric-http-error-handler-interceptor.service.ts, Fabric.Authorization.AccessControl/src/app/services/interceptors/fabric-http-request-interceptor.service.ts, Fabric.Authorization.AccessControl/src/app/services/interceptors/index.ts
..and to allow for installing applications to provide a configuration object
=> some updates to the access control module to get the packaging to work

Fabric.Authorization.API/Models/Search/MemberSearchResponse.cs, Fabric.Authorization.API/Models/Search/MemberSearchResponseExtensions.cs, Fabric.Authorization.API/Modules/MemberSearchModule.cs, Fabric.Authorization.API/Services/MemberSearchService.cs, Fabric.Authorization.FunctionalTests/tests/authorizationtests.js, Fabric.Authorization.IntegrationTests/Modules/MemberSearchTests.cs
=> add total count property to the member search response. 

Fabric.Authorization.AccessControl/src/app/modules/access-control/member-add/member-add.component.ts
=> export a couple interfaces so packagr can package

Fabric.Authorization.IntegrationTests/Modules/MemberSearchTests.cs, Fabric.Authorization.Persistence.SqlServer/EntityModels/User.cs, Fabric.Authorization.Persistence.SqlServer/Extensions/ModelBuilderExtensions.cs, Fabric.Authorization.Persistence.SqlServer/Mappers/GroupMapperProfile.cs, Fabric.Authorization.Persistence.SqlServer/Mappers/UserMapperProfile.cs, Fabric.Authorization.Persistence.SqlServer/Stores/SqlServerRoleStore.cs
use the filtered property collections on user and group when mapping entity to domain model
update the role entity query to use AsNoTracking
=> dont return deleted role join entities. 

Fabric.Authorization.AccessControl/src/app/app.module.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/access-control.module.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/member-list/member-list.component.html, Fabric.Authorization.AccessControl/src/app/modules/access-control/member-list/member-list.component.spec.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/member-list/member-list.component.ts
Fix issues reported by Victor during QA review of the AccessControl list page.
=> QA review changes

Fabric.Authorization.API/scripts/Install-Authorization-Windows.ps1
=> Auto install IIS Rewrite

Fabric.Authorization.API/scripts/Install-Authorization-Windows.ps1
Removing migration from EDW Admin to DOS Admin during registration script. This is specifically for the 18.1 hotfix.
=> Removing auto migration of admin roles

Fabric.Authorization.API/scripts/Install-Authorization-Windows.ps1
Had to cast and trim, trim/cast alone were not enough
=> No space when storing authorization client secret

Fabric.Authorization.API/scripts/Install-Authorization-Windows.ps1
Backport client/api secret reset into 18.1
=> Backport secret reset to 18.1

Fabric.Authorization.API/scripts/Install-Authorization-Windows.ps1
Adapted code from https://github.com/HealthCatalyst/Fabric.Authorization/commit/823c2e946514a5915c1ed7ebec6ed883c1276406#diff-e81f46f8c24fc699274b63f0d42b2674
Created a function to get all users from EDWAdmin.  The neat thing is that this should only be users.  Groups should not have a role 'EDW Admin'.  The function could be reused, so I left it with a generic 'Get-EdwAdminUsersAndGroups', but could rename it to 'Get-EdwAdminUsers'.
After getting the users, we call 'Add-ListOfUsersToDosAdminRole' which is very similar to 'Add-AccountToDosAdminRole', but we do not check AD to verify that there is a user or group of that name.  Moreover it processes a list.  The for loop will swallow exceptions, but will print the error for the user in the script.  If the user exists, we will catch the 409 …
=> Migrate all users from EDWAdmin to DosAdmin.

Fabric.Authorization.API/scripts/Install-Authorization-Windows.ps1
Remove Add-DiscoveryRegistration (moved into fabric utils)
Move Add-DiscoveryRegistration to after site deploy step so dll exists
=> Register Authorization BuildNumber with discovery

Fabric.Authorization.API/scripts/Install-Authorization-Windows.ps1
Updating 18.1
Move registration step to fabric utils, auth passes version to register function
=> Move DiscoveryRegistration to fabric utils

Fabric.Authorization.API/scripts/Install-Authorization-Windows.ps1, Fabric.Authorization.IntegrationTests/Modules/MemberSearchTests.cs
Move registration step after app install so app.dll exists to get version
=> Move discovey registration after app install

Fabric.Authorization.Client.FunctionalTests/AuthorizationClientTests.cs, Fabric.Authorization.Client.FunctionalTests/FunctionalTestFixture.cs, Fabric.Authorization.Client.UnitTests/AuthorizationClientTests.cs, Fabric.Authorization.Client.UnitTests/Routes/UserRouteTests.cs, Fabric.Authorization.Client/AuthorizationClient.cs, Fabric.Authorization.Client/ClientConstants.cs, Fabric.Authorization.Client/Fabric.Authorization.Client.csproj, Fabric.Authorization.Client/Routes/UserRoute.cs
Adding 3 methods: GetPermissionsForCurrentUser
- GetPermissionsForCurrentUser with grain and securable Items as parameters
- DoesUserHavePermissions doing a query with GetPermissionsForCurrentUser 
- DoesUserHavePermissions with UserPermissionsModel you might already have
=> Add Permission check methods

Catalyst.Fabric.Authorization.Client.UnitTests/Catalyst.Fabric.Authorization.Client.UnitTests.csproj, Fabric.Authorization.API/Models/GrainApiModel.cs, Fabric.Authorization.API/Models/ModelExtensions.cs, Fabric.Authorization.API/Modules/GrainsModule.cs, Fabric.Authorization.AccessControl/src/app/app.component.spec.ts, Fabric.Authorization.AccessControl/src/app/app.module.ts, Fabric.Authorization.AccessControl/src/app/models/grain.model.ts, Fabric.Authorization.AccessControl/src/app/models/securableItem.model.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/access-control-routing.module.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/access-control.module.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/grain-list/grain-list.component.html, Fabric.Authorization.AccessControl/src/app/modules/access-control/grain-list/grain-list.component.scss, Fabric.Authorization.AccessControl/src/app/modules/access-control/grain-list/grain-list.component.spec.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/grain-list/grain-list.component.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/services.mock.module.ts, Fabric.Authorization.AccessControl/src/app/services/fabric-auth-grain.service.mock.ts, Fabric.Authorization.AccessControl/src/app/services/fabric-auth-grain.service.spec.ts, Fabric.Authorization.AccessControl/src/app/services/fabric-auth-grain.service.ts, Fabric.Authorization.AccessControl/src/environments/environment.default.ts, Fabric.Authorization.Domain/Services/GrainService.cs, Fabric.Authorization.Domain/Stores/IGrainStore.cs, Fabric.Authorization.Domain/Validators/GrainValidator.cs, Fabric.Authorization.Persistence.SqlServer/Stores/SqlServerGrainStore.cs, Fabric.Authorization.UnitTests/Fabric.Authorization.UnitTests.csproj, Fabric.Authorization.UnitTests/Grains/GrainModuleTests.cs, Fabric.Authorization.UnitTests/Grains/GrainServiceTests.cs, Fabric.Authorization.UnitTests/Grains/SecurableItemExtension.cs, Fabric.Authorization.UnitTests/Mocks/MockGrainStore.cs
I have created a left handed nav with sub items.  
Tried the cashmere list, but it felt like it was restrictive on multiline items.  You had to explicited label each line.  If this gets recursive, this may be a big issue.  Of course if there is some advice, let me know.  Link to the list:  https://cashmere.healthcatalyst.net/components/list
Also, this is just a shell.  I dont have the service to call the API yet.  I just wanted to make sure the general look was acceptable before proceeding.
=> added initial screen for left hand navigation 

Fabric.Authorization.AccessControl/package-lock.json, Fabric.Authorization.AccessControl/setup-access-control.sh, Fabric.Authorization.AccessControl/src/app/modules/access-control/grain-list/grain-list.component.spec.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/grain-list/grain-list.component.ts
- Added -v to be verbose for the setup script, just incase you need to know if it success or fails
- Added tests for GrainListComponent
- minor tweaks caused by testing
=> Add tests and minor fixes

Fabric.Authorization.API/Infrastructure/Middleware/AngularMiddleware.cs
Changed code to get the right client url.
Any suggestions on how to test this.  I will try to get something going by the morning.
=> Uri class will not append the url correctly. 

Fabric.Authorization.AccessControl/src/app/modules/access-control/grain-list/grain-list.component.spec.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/grain-list/grain-list.component.ts, Fabric.Authorization.AccessControl/src/app/services/fabric-auth-grain.service.mock.ts
Do not switch nodes if the node being selected is a parent grain node
=> Fix endless spinner when grain is selected and attempt to order

Fabric.Authorization.AccessControl/src/index.html
This reverts commit 82144e75d38a6ef32ef7545168405be48d493b73.
=> Revert "favicon off absolute path from root for edge(/ie bookmarking)"

Fabric.Authorization.IntegrationTests/Modules/ChildGroupsTests.cs, Fabric.Authorization.IntegrationTests/Modules/UserTests.cs
ChildGroupTest was failing when checking permission count due to previous UserTest using the same subjectId and adding a permission
=> Add Guid to subjectId's to be unique

Fabric.Authorization.AccessControl/README.md, Fabric.Authorization.AccessControl/setup-dependencies.ps1
Installs and uninstalls the following:
1. node modules - this is to get rid of specific platform dependencies
2. node
3. angular
4. typescript
5. npm install
There may be one more step left.  I noticed node-sass needs to be precompiled before you can use access-control.  So i may need to fix that up some.
=> Added script to install node, npm, angular and more.

Fabric.Authorization.API/scripts/Install-Authorization-Utilities.psm1, Fabric.Authorization.API/scripts/Install-Authorization-Utilities.tests.ps1, Fabric.Authorization.API/scripts/Install-Authorization-Windows.ps1, Fabric.Authorization.API/scripts/Install-Authorization.ps1
Added SQL script to Add-UserOrGroupToEdwAdmin.  Double check my SQL and see if it sucks
Added function Add-AccountToEDWAdmin to add a user to EDWAdmin
Added function call right below adding the user to DosAdmin
I need to double check if the user exists to not add them
=> Added function to add user to edwAdmin

Fabric.Authorization.AccessControl/src/app/app.component.spec.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/custom-group/custom-group.component.spec.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/member/member.component.spec.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/member/member.component.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/services.mock.module.ts, Fabric.Authorization.AccessControl/src/app/navbar/navbar.component.spec.ts, Fabric.Authorization.AccessControl/src/app/services/fabric-auth-group.service.mock.ts, Fabric.Authorization.AccessControl/src/app/services/global/alert.service.mock.ts
I'm adding similar tests for the custom group component.
=> added tests to ensure sync alert is invoked when sync error occurs

Fabric.Authorization.API/scripts/Install-Authorization-Utilities.psm1, Fabric.Authorization.API/scripts/Install-Authorization.ps1
- Fixed incorrect prompt
-Added requires statements to Install-Authorization.ps1
=> Small install script fixes

Fabric.Authorization.AccessControl/src/app/modules/access-control/custom-group/custom-group.component.ts
=> small change to show the same error and not undefined when removing group name

Fabric.Authorization.AccessControl/src/app/services/access-control-config.service.mock.ts, Fabric.Authorization.AccessControl/src/app/services/fabric-auth-edwadmin.service.spec.ts
Some simple tests for the fabric-auth-edwadmin sync service
=> Sync service tests

Fabric.Authorization.AccessControl/src/app/services/global/services.service.ts
updating code to fix access control matching url issues. TDD tests have been checked in previously.
=> updating code to fix access control matching url issues. TDD tests have been checked in previously.

Fabric.Authorization.API/scripts/Install-Authorization-Utilities.psm1
=> version change

Fabric.Authorization.Domain/Models/IUser.cs, Fabric.Authorization.Domain/Models/User.cs, Fabric.Authorization.Persistence.SqlServer/EntityModels/User.cs
fix an issue with a nullable column in the database but not in the model
=> fix an issue with a nullable column in the database but not in the model

Fabric.Authorization.API/scripts/AzureADUsers-Migration.ps1
=> script changes

Fabric.Authorization.AccessControl/src/app/constants/principal-constants.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/custom-group/custom-group.component.spec.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/custom-group/custom-group.component.ts, Fabric.Authorization.AccessControl/src/app/modules/access-control/member/member.component.html, Fabric.Authorization.AccessControl/src/app/modules/access-control/member/member.component.ts, Fabric.Authorization.AccessControl/src/app/services/name-display.service.spec.ts, Fabric.Authorization.AccessControl/src/app/services/name-display.service.ts
member-list and custom-group components to use the name service
=> Move getPrincipalNameToDisplay logic into service

Fabric.Authorization.AccessControl/README.md
Added a few more steps for the documentation as to how to debug Authorization.
=> Added a few more steps

Fabric.Authorization.AccessControl/e2e/admin-tests/admin-user.spec.ts, Fabric.Authorization.AccessControl/e2e/pages/member-list.page.ts, Fabric.Authorization.AccessControl/e2e/pages/member.page.ts, Fabric.Authorization.AccessControl/package-lock.json, Fabric.Authorization.AccessControl/package.json, Fabric.Authorization.AccessControl/protractor.conf.js
Had promises not waiting so stuff would occasionally happen out of order.
Ran npm audit fix for the vulnerabilities that came up as well.
There is still an issue with the save button not loading correctly.  This seems to be an issue with the access control ui code rather than the functional tests however.  The issue occurred in 6/50 runs.  Possibly some other race condition happening in code when going fast
=> Update functional tests to be more consistent

Fabric.Authorization.API/scripts/install.config
applicationEndpoint -> applicationEndPoint
=> changed default applicationEndPoint casing

Fabric.Authorization.API/scripts/Install-Authorization-Utilities.psm1, Fabric.Authorization.API/scripts/Install-Authorization.ps1, Fabric.Authorization.API/scripts/tests/Get-AuthorizationFabricInstallerSecret.tests.ps1
Update to latest DIU
Add Get-AuthorizationFabricInstallerSecret tests
=> Update Authorization install to use DIU for configs

Fabric.Authorization.API/scripts/AzureAD-Utilities.psm1, Fabric.Authorization.API/scripts/Install-Authorization-Utilities.psm1
=> latest DIU

Fabric.Authorization.API/scripts/AzureAD-Utilities.psm1, Fabric.Authorization.API/scripts/Install-Authorization-Utilities.psm1
=> update DIU 1.x should be 1.5

Fabric.Authorization.API/scripts/Install-Authorization-Utilities.psm1
=> update DIU 1.4

Fabric.Authorization.API/scripts/Install-Authorization.ps1
Updated install script to pull latest version of DOS Install Utilities
=> Updated Install script to pull latest DIU Version

Fabric.Authorization.API/scripts/Install-Authorization-Utilities.psm1
add identity.searchusers scope
=> add identity.searchusers scope
